
Table sections {
  id integer [pk, increment]
  academic_level_id integer [not null]
  identifier varchar [not null]
}


Table groups {
  id integer [pk, increment]
  number integer [not null]
  section_id integer [not null]
}


Table academic_levels {
  id integer [pk, increment]
  level integer [not null]
  degree_program_id integer [not null]
}


// 2. Academic Structure


Table courses {
  id integer [pk, increment]
  name varchar [not null]
}


Table professors {
  id integer [pk, increment]
  surname varchar [not null]
  name varchar [not null]
  phone_number varchar
  email varchar [not null]
}


Table course_assistant {
  id integer [pk, increment]
  course_id integer [not null]
  group_id integer [not null]
  professor_id integer [not null]
  role varchar [not null]
}

Table course_teacher {
  id integer [pk, increment]
  course_id integer [not null]
  professor_id integer [not null]
  section_id integer [not null]
}


Table semesters {
  id integer [pk, increment]
  academic_level_id integer [not null]
  number integer [not null]
}


Table semester_courses {
  id integer [pk, increment]
  semester_id integer [not null]
  course_id integer [not null]
  has_td boolean [not null]
  num_td integer [not null]
  has_tp boolean [not null]
  num_tp integer [not null]
  coef integer
}


Ref: semester_courses.course_id > courses.id

Ref: semester_courses.semester_id > semesters.id

Ref: semesters.academic_level_id > academic_levels.id

Ref: course_assistant.course_id > semester_courses.id

Ref: course_assistant.group_id > groups.id

Ref: course_assistant.professor_id > professors.id

Ref: course_teacher.professor_id > professors.id

Ref: course_teacher.course_id > semester_courses.id

Ref: course_teacher.section_id > sections.id
