

// 1. Pedagogical Structure

// We mean by 'Pedagogical' the hierarchy of groupings that students are
// divided in.
//
// The structure is pretty straightforward. A specialty has academic levels
// that each contain sections which are in turn also divided in groups.


Table students {
  id integer [pk, increment]
  group_id integer [not null]
  surname varchar [not null]
  name varchar
  matricule varchar
  email varchar
}


Table groups {
  id integer [pk, increment]
  number integer [not null]
  section_id integer [not null]
}


Table sections {
  id integer [pk, increment]
  academic_level_id integer [not null]
  identifier varchar [not null]
}


Table academic_levels {
  id integer [pk, increment]
  level integer [not null]
  degree_program_id integer [not null]
}


Table degree_programs {
  id integer [pk, increment]
  // e.g. "Intelligence Artificiel" or "Science et Technologies"
  name varchar [not null]
  // an abreviation of the name e.g. "AI" or "GL" for "Genie Logiciel"
  acronyme varchar [not null]
  // wether it's a Master's or a Licence/Bachelor's degree
  cycle varchar [not null]
}


Ref: students.group_id > groups.id

Ref: groups.section_id > sections.id

Ref: sections.academic_level_id > academic_levels.id

Ref: academic_levels.degree_program_id > degree_programs.id


